#./tools/dist_train.sh configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_reid_1000.py 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_reid_1000_softmax.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_reid_1000_fpncat.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_multiscale.py --gpu-ids 1
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500.py --gpu-ids 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1.py --gpu-ids 3
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage12all.py --gpu-ids 1
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage12all_tri.py --gpu-ids 3
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage12.py --gpu-ids 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat.py --gpu-ids 4
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1000_stage1_fpncat_dcn.py --gpu-ids 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_2000_stage1_fpncat_dcn.py --gpu-ids 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1000_stage1_fpncat_dcn_tri.py --gpu-ids 4
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_tri.py --gpu-ids 4
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_tri_queue.py --gpu-ids 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1000_stage1_fpncat_dcn_tri_queue.py --gpu-ids 5
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_twostream.py --gpu-ids 3
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1000_stage1_fpncat_dcn_twostream.py --gpu-ids 1
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_twostream_halfdcn.py --gpu-ids 4
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_l4.py --gpu-ids 4
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_full.py --gpu-ids 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_512.py --gpu-ids 1
#python tools/train.py configs/hrnet/fcos_hrnetv2p_w18_gn-head_mstrain_640-800_4x4_2x_cuhk.py --gpu-ids 5
#python tools/train.py configs/hrnet/fcos_hrnetv2p_w18_gn-head_mstrain_640-800_4x4_2x_cuhk_all.py --gpu-ids 6
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_multiscale_stage1.py --gpu-ids 4
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_dcn_stage1.py --gpu-ids 4
#python tools/train.py configs/reppoints/reppoints_minmax_r50_fpn_gn-neck+head_1x_cuhk.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_reid_1000_tri.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_reid_normaware_1000.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_reid_1000.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_reid_roi_1000.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_1000.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_cuhk_1500.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_mot_reid.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_mot_reid_coco.py
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_mot_reid_coco_softmax.py
#./tools/dist_train.sh configs/fcos/fcos_x101_64x4d_fpn_gn-head_mstrain_640-800_4x2_2x_mot.py 8
#./tools/dist_train.sh configs/hrnet/fcos_hrnetv2p_w40_gn-head_mstrain_640-800_4x4_2x_mot.py 8
#./tools/dist_train.sh configs/hrnet/fcos_hrnetv2p_w18_gn-head_mstrain_640-800_4x4_2x_mot.py 8
#./tools/dist_train.sh configs/hrnet/fcos_hrnetv2p_w18_gn-head_mstrain_640-800_4x4_2x_mot_detection.py 8
#./tools/dist_train.sh configs/hrnet/fcos_hrnetv2p_w32_gn-head_mstrain_640-800_4x4_2x_mot_detection.py 8
#./tools/dist_train.sh configs/reppoints/reppoints_minmax_r50_fpn_gn-neck+head_1x_cuhk.py 8
#./tools/dist_train.sh configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid.py 8
#python tools/train.py configs/reppoints/reppoints_minmax_r50_fpn_gn-neck+head_1x_cuhk_reid.py
#./tools/dist_train.sh configs/reppoints/reppoints_minmax_r50_fpn_gn-neck+head_1x_cuhk_reid.py 8
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_norelu.py --gpu-ids 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_bdg2.py --gpu-ids 3
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24.py --gpu-ids 4
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_fdg2.py --gpu-ids 5
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_lconv3.py --gpu-ids 6
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_bs8.py --gpu-ids 7
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_tri.py --gpu-ids 1
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_bs2.py --gpu-ids 5
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_fullqueue.py --gpu-ids 6
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_1wqueue.py --gpu-ids 5
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_2kqueue.py --gpu-ids 3
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_2kfullqueue.py --gpu-ids 2
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_cos.py --gpu-ids 7
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_queue32.py --gpu-ids 6
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale.py --gpu-ids 7
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_single.py --gpu-ids 6
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch36_multiscale.py --gpu-ids 6 >work_dirs/log_epoch36.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_lr002.py --gpu-ids 5 >work_dirs/log_epoch24_lr002.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_lr0005.py --gpu-ids 4 >work_dirs/log_epoch24_lr0005.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch12_multiscale.py --gpu-ids 3 >work_dirs/log_epoch12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch12_multiscale_stage12.py --gpu-ids 2 >work_dirs/log_epoch12_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_stage12.py --gpu-ids 1 >work_dirs/log_epoch24_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_lr0008.py --gpu-ids 5 >work_dirs/log_epoch24_lr0008.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch36_multiscale_stage12.py --gpu-ids 7 >work_dirs/log_epoch36_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_lr0008_stage12.py --gpu-ids 5 >work_dirs/log_epoch24_lr0008_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch36_multiscale_lr0008_stage12.py --gpu-ids 4 >work_dirs/log_epoch36_lr0008_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch36_multiscale_lr0008.py --gpu-ids 3 >work_dirs/log_epoch36_lr0008.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal.py --gpu-ids 5 >work_dirs/log_epoch24_focal.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch12_multiscale_newoim.py --gpu-ids 2 >work_dirs/log_epoch12_newoim.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch12_multiscale_newoimsmr.py --gpu-ids 6 >work_dirs/log_epoch12_newoim_smr.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr.py --gpu-ids 7 >work_dirs/log_epoch24_newoim_smr.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_new.py --gpu-ids 3 >work_dirs/log_epoch24_newoim_new.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_new.py --gpu-ids 4 >work_dirs/log_epoch24_newoim_smr_new.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal.py --gpu-ids 1 >work_dirs/log_epoch24_newoim_smr_new_focal.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal.py --gpu-ids 0 >work_dirs/log_epoch24_newoim_new_focal.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_hoim.py --gpu-ids 6 >work_dirs/log_epoch24_hoim.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_bg-2.py --gpu-ids 2 >work_dirs/log_epoch24_newoim_smr_bg-2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch36_multiscale_focal.py --gpu-ids 5 >work_dirs/log_epoch36_focal.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4.py --gpu-ids 7 >work_dirs/log_epoch24_focal_4x.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_stage12.py --gpu-ids 4 >work_dirs/log_epoch24_focal_4x_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_stage12.py --gpu-ids 3 >work_dirs/log_epoch24_focal_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x8_stage12.py --gpu-ids 1 >work_dirs/log_epoch24_focal_x8_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x8.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x8.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_bg-2.py --gpu-ids 6 >work_dirs/log_epoch24_newoim_new_focal_bg-2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_bg-2.py --gpu-ids 2 >work_dirs/log_epoch24_newoim_smr_new_focal_bg-2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2.py --gpu-ids 7 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x3.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x3.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x5.py --gpu-ids 1 >work_dirs/log_epoch24_focal_x5.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x5_stage12.py --gpu-ids 3 >work_dirs/log_epoch24_focal_x5_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x3_stage12.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x3_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x2_bg-2.py --gpu-ids 2 >work_dirs/log_epoch24_focal_x2_bg-2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x2_stage12_bg-2.py --gpu-ids 6 >work_dirs/log_epoch24_focal_x2_stage12_bg-2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_x4_bg-2.py --gpu-ids 7 >work_dirs/log_epoch24_newoim_new_focal_x4_bg-2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_x4_bg-2_stage2.py --gpu-ids 6 >work_dirs/log_epoch24_newoim_new_focal_x4_bg-2_stage2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_stage2.py --gpu-ids 2 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_stage2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_lconv3dcn.py --gpu-ids 7 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_lconv3dcn.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_lconv1dcn.py --gpu-ids 5 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_lconv1dcn.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_dcndcn.py --gpu-ids 4 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_dcndcn.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_tri.py --gpu-ids 3 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_tri.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_triqueue.py --gpu-ids 1 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_triqueue1e-8.py --gpu-ids 0 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_triqueue1e-8.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_sub.py --gpu-ids 6 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_sub.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoimsmr_newfocal_x4_bg-2_sub_triqueue.py --gpu-ids 2 >work_dirs/log_epoch24_newoim_smr_new_focal_x4_bg-2_sub_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_x4_bg-2_lconv3dcn.py --gpu-ids 7 >work_dirs/log_epoch24_newoim_new_focal_x4_bg-2_lconv3dcn.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_x4_bg-2_lconv1dcn.py --gpu-ids 5 >work_dirs/log_epoch24_newoim_new_focal_x4_bg-2_lconv1dcn.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv1dcn.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_lconv1dcn.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn.py --gpu-ids 3 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_triqueue.py --gpu-ids 1 >work_dirs/log_epoch24_focal_x4_bg-2_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_triqueuenograd.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x4_bg-2_triqueuenograd.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_x4_bg-2_sub.py --gpu-ids 6 >work_dirs/log_epoch24_newoim_new_focal_x4_bg-2_sub.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_x4_bg-2_sub_triqueue.py --gpu-ids 2 >work_dirs/log_epoch24_newoim_new_focal_x4_bg-2_sub_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_fpn3.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_fpn3.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_fpn1.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_fpn1.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub.py --gpu-ids 1 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub1_triqueue.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub1_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_x4_bg-2_lconv3dcn_triqueue.py --gpu-ids 3 >work_dirs/log_epoch24_newoim_new_focal_x4_bg-2_lconv3dcn_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_newoim_newfocal_x4_bg-2_lconv3dcn_sub1_triqueue.py --gpu-ids 6 >work_dirs/log_epoch24_newoim_new_focal_x4_bg-2_lconv3dcn_sub1_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_fpn3_sub.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_fpn3_sub.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_fpn3_sub1_triqueue.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_fpn3_sub1_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_fpn3_sub_triqueue.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_fpn3_sub_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_fpn3_triqueue.py --gpu-ids 2 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_fpn3_triqueue.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_fpn3_sub1.py --gpu-ids 1 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_fpn3_sub1.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_fpn3_tri.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_fpn3_tri.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage2.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage3.py --gpu-ids 6 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage3.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage12.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage123.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage123.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage23.py --gpu-ids 3 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage23.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no123.py --gpu-ids 2 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no123.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no1.py --gpu-ids 1 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no1.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no12.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no2.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no3.py --gpu-ids 6 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no3.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no23.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no23.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no13.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no13.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn1.py --gpu-ids 3 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn1.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0.py --gpu-ids 2 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn12.py --gpu-ids 1 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn12.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_res101.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_res101.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_tri.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_tri.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_res18.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_res18.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_t1.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_t1.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_t2.py --gpu-ids 6 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_t2.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_t3.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_t3.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_t3_1.py --gpu-ids 3 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_t3_1.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_t4.py --gpu-ids 2 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_t4.txt 2>&1 &
#python tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_twostream.py --gpu-ids 2
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no123_dcn0.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no123_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0_new.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_dcn0_new.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no1_dcn0.py --gpu-ids 6 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no1_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no2_dcn0.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no2_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no3_dcn0.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no3_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no13_dcn0.py --gpu-ids 3 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no13_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no23_dcn0.py --gpu-ids 1 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no23_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_no12_dcn0.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_no12_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage123_dcn0.py --gpu-ids 2 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage123_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage12_dcn0.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage12_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage23_dcn0.py --gpu-ids 3 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage23_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage2_dcn0.py --gpu-ids 6 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage2_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage3_dcn0.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_stage3_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_t1_dcn0.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_t1_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_t2_dcn0.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_t2_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_triqueue_t3_dcn0.py --gpu-ids 3 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_triqueue_t3_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_tri_dcn0.py --gpu-ids 0 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_tri_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_lconv3dcn_sub_dcn0.py --gpu-ids 2 >work_dirs/log_epoch24_focal_x4_bg-2_lconv3dcn_sub_dcn0.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_nta_nra_nsa.py --gpu-ids 7 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_nta_nra_nsa.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_nta_nra.py --gpu-ids 6 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_nta_nra.txt 2>&1 &
nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_nta_nsa.py --gpu-ids 5 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_nta_nsa.txt 2>&1 &
#nohup python -u tools/train.py configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_4x4_1x_cuhk_reid_1500_stage1_fpncat_dcn_epoch24_multiscale_focal_x4_bg-2_sub_triqueue_nra_nsa.py --gpu-ids 4 >work_dirs/log_epoch24_focal_x4_bg-2_sub_triqueue_nra_nsa.txt 2>&1 &


